# Generated by Django 3.2.4 on 2021-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('points', models.IntegerField()),
                ('ratings', models.IntegerField()),
            ],
        ),
    ]
