# Generated by Django 3.2.3 on 2021-06-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('surname', models.TextField(null=True)),
                ('gender', models.TextField(null=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
