# Generated by Django 3.2.3 on 2021-12-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='equipmentpost',
            name='pathToEquipmentPostImage',
            field=models.URLField(blank=True, verbose_name='https://nzftk20rg4.execute-api.eu-central-1.amazonaws.com/v1/lodobucket451?file=<property object at 0x000001F3B34F0270>'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='pathToEventImage',
            field=models.URLField(blank=True, verbose_name='https://nzftk20rg4.execute-api.eu-central-1.amazonaws.com/v1/lodobucket451?file=<property object at 0x000001F3B34F0270>'),
        ),
    ]
