# Generated by Django 3.2.3 on 2021-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('link', models.CharField(max_length=2083, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(max_length=2083, null=True)),
            ],
        ),
    ]
