# Generated by Django 3.2.4 on 2021-06-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210605_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_post_id', models.IntegerField()),
                ('date_time', models.CharField(max_length=100)),
                ('participation_limit', models.IntegerField()),
                ('spectator_limit', models.IntegerField()),
                ('rule', models.CharField(max_length=100)),
                ('equipment_requirement', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('skill_requirement', models.CharField(max_length=100)),
                ('repeating_frequency', models.IntegerField()),
            ],
        ),
    ]
