# Generated by Django 3.2.4 on 2021-06-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_eventpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrenctCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=100)),
                ('base_total', models.FloatField()),
                ('target_currency', models.CharField(max_length=100)),
                ('target_result', models.FloatField()),
            ],
        ),
    ]
