# Generated by Django 3.2.4 on 2021-06-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_currenctcurrency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrenctCurrency',
            new_name='CurrentCurrency',
        ),
    ]
