# Generated by Django 3.2.4 on 2021-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_currenctcurrency_currentcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcurrency',
            name='base_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currentcurrency',
            name='target_result',
            field=models.IntegerField(),
        ),
    ]
