# Generated by Django 3.2.4 on 2021-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('max_player', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=100)),
                ('base_total', models.IntegerField()),
                ('target_currency', models.CharField(max_length=100)),
                ('target_result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_post_id', models.IntegerField()),
                ('date_time', models.CharField(max_length=100)),
                ('participation_limit', models.IntegerField()),
                ('spectator_limit', models.IntegerField()),
                ('rule', models.CharField(max_length=100)),
                ('equipment_requirement', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('skill_requirement', models.CharField(max_length=100)),
                ('repeating_frequency', models.IntegerField()),
            ],
        ),
    ]
